"""Added gender_types

Revision ID: 8473b13e21e1
Revises: a84c62e39621
Create Date: 2024-12-23 16:23:45.229048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8473b13e21e1'
down_revision = 'a84c62e39621'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('male', 'female', 'others', name='gender_types'),
               existing_nullable=False)
        batch_op.execute("CREATE TYPE gender_types AS ENUM ('male', 'female', 'others')")
        batch_op.execute("ALTER TABLE \"user\" ALTER COLUMN gender TYPE gender_types USING gender::gender_types")


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('gender',
               existing_type=sa.Enum('male', 'female', 'others', name='gender_types'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
