"""Add role_types and gender_types enums

Revision ID: a84c62e39621
Revises:
Create Date: 2024-12-23 16:13:57.475563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a84c62e39621'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.drop_constraint('leaderboard_quiz_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('leaderboard_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_is_read'), ['is_read'], unique=False)
        batch_op.drop_constraint('notification_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_question_quiz_id'), ['quiz_id'], unique=False)
        batch_op.drop_constraint('question_quiz_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'category', ['category_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('quiz_history', schema=None) as batch_op:
        batch_op.drop_constraint('quiz_history_quiz_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('quiz_history_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz', ['quiz_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('user', 'admin', name='role_types'),
               existing_nullable=True)
        batch_op.execute("ALTER TABLE \"user\" ALTER COLUMN role TYPE role_types USING role::role_types")
        batch_op.drop_constraint('user_email_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    with op.batch_alter_table('user_answer', schema=None) as batch_op:
        batch_op.drop_constraint('user_answer_quiz_history_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('user_answer_question_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'quiz_history', ['quiz_history_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'question', ['question_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_answer', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('user_answer_question_id_fkey', 'question', ['question_id'], ['id'])
        batch_op.create_foreign_key('user_answer_quiz_history_id_fkey', 'quiz_history', ['quiz_history_id'], ['id'])

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.create_unique_constraint('user_email_key', ['email'])
        batch_op.alter_column('role',
               existing_type=sa.Enum('user', 'admin', name='role_types'),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
        batch_op.drop_column('gender')

    with op.batch_alter_table('quiz_history', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quiz_history_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('quiz_history_quiz_id_fkey', 'quiz', ['quiz_id'], ['id'])

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('category_id')

    with op.batch_alter_table('question', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('question_quiz_id_fkey', 'quiz', ['quiz_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_question_quiz_id'))

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('notification_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_notification_is_read'))

    with op.batch_alter_table('leaderboard', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('leaderboard_user_id_fkey', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('leaderboard_quiz_id_fkey', 'quiz', ['quiz_id'], ['id'])

    # ### end Alembic commands ###
