"""Removed: DOB & Gender

Revision ID: b584e9742c47
Revises: 25c48596ffb8
Create Date: 2025-01-17 16:34:10.483749

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b584e9742c47'
down_revision = '25c48596ffb8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_of_birth')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', postgresql.ENUM('male', 'female', 'others', name='gender_types'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
